title: Diego E F Biavati
description: Página Pessoal
author: Diego Eduardo Ferreira Biavati
url: https://diegobiavati.github.io
google_analytics: UA-117510135-1
plugins:
  - jekyll-feed
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
twitter:
  - username: diegobiavati
